"""
Catálogo de instituições de ensino e órgãos educacionais federais (referência para prospecção).
Fonte-base: estrutura oficial da rede federal (MEC) — atualize conforme novas instituições.
"""

from __future__ import annotations

# Órgãos federais de educação (MEC / articulação da rede).
ORGANISMOS_EDUCACAO_FEDERAL: tuple[tuple[str, str, str], ...] = (
    (
        "inep",
        "Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira",
        "INEP",
    ),
    (
        "fnde",
        "Fundo Nacional de Desenvolvimento da Educação",
        "FNDE",
    ),
    (
        "conif",
        "Conselho Nacional das Instituições da Rede Federal de Educação Profissional, Científica e Tecnológica",
        "CONIF",
    ),
    (
        "sesu",
        "Secretaria de Educação Superior",
        "SESU / MEC",
    ),
    (
        "setec",
        "Secretaria de Educação Profissional e Tecnológica",
        "SETEC / MEC",
    ),
)

# Universidades federais (sigla, nome oficial, UF da sede principal).
UNIVERSIDADES_FEDERAIS: tuple[tuple[str, str, str], ...] = (
    ("UnB", "Universidade de Brasília", "DF"),
    ("UFGD", "Universidade Federal da Grande Dourados", "MS"),
    ("UFG", "Universidade Federal de Goiás", "GO"),
    ("UFMT", "Universidade Federal de Mato Grosso", "MT"),
    ("UFMS", "Universidade Federal de Mato Grosso do Sul", "MS"),
    ("UFCAT", "Universidade Federal de Catalão", "GO"),
    ("UFJ", "Universidade Federal de Jataí", "GO"),
    ("UFR", "Universidade Federal de Rondonópolis", "MT"),
    ("UFBA", "Universidade Federal da Bahia", "BA"),
    ("UFSB", "Universidade Federal do Sul da Bahia", "BA"),
    ("UFRB", "Universidade Federal do Recôncavo da Bahia", "BA"),
    ("UNILAB", "Universidade Federal da Integração Internacional da Lusofonia Afro-Brasileira", "CE"),
    ("UFPB", "Universidade Federal da Paraíba", "PB"),
    ("UFCA", "Universidade Federal do Cariri", "CE"),
    ("UFAL", "Universidade Federal de Alagoas", "AL"),
    ("UFCG", "Universidade Federal de Campina Grande", "PB"),
    ("UFPE", "Universidade Federal de Pernambuco", "PE"),
    ("UFS", "Universidade Federal de Sergipe", "SE"),
    ("UFC", "Universidade Federal do Ceará", "CE"),
    ("UFMA", "Universidade Federal do Maranhão", "MA"),
    ("UFOB", "Universidade Federal do Oeste da Bahia", "BA"),
    ("UFPI", "Universidade Federal do Piauí", "PI"),
    ("UFRN", "Universidade Federal do Rio Grande do Norte", "RN"),
    ("UNIVASF", "Universidade Federal do Vale do São Francisco", "PE"),
    ("UFRPE", "Universidade Federal Rural de Pernambuco", "PE"),
    ("UFERSA", "Universidade Federal Rural do Semi-Árido", "RN"),
    ("UNIR", "Universidade Federal de Rondônia", "RO"),
    ("UFRR", "Universidade Federal de Roraima", "RR"),
    ("UFAC", "Universidade Federal do Acre", "AC"),
    ("UNIFAP", "Universidade Federal do Amapá", "AP"),
    ("UFAM", "Universidade Federal do Amazonas", "AM"),
    ("UFOPA", "Universidade Federal do Oeste do Pará", "PA"),
    ("UFPA", "Universidade Federal do Pará", "PA"),
    ("UFT", "Universidade Federal do Tocantins", "TO"),
    ("UFRA", "Universidade Federal Rural da Amazônia", "PA"),
    ("UNIFESSPA", "Universidade Federal do Sul e Sudeste do Pará", "PA"),
    ("UNIFAL-MG", "Universidade Federal de Alfenas", "MG"),
    ("UNIFEI", "Universidade Federal de Itajubá", "MG"),
    ("UFJF", "Universidade Federal de Juiz de Fora", "MG"),
    ("UFLA", "Universidade Federal de Lavras", "MG"),
    ("UFMG", "Universidade Federal de Minas Gerais", "MG"),
    ("UFOP", "Universidade Federal de Ouro Preto", "MG"),
    ("UFSCar", "Universidade Federal de São Carlos", "SP"),
    ("UFSJ", "Universidade Federal de São João del-Rei", "MG"),
    ("UNIFESP", "Universidade Federal de São Paulo", "SP"),
    ("UFU", "Universidade Federal de Uberlândia", "MG"),
    ("UFV", "Universidade Federal de Viçosa", "MG"),
    ("UFABC", "Universidade Federal do ABC", "SP"),
    ("UFES", "Universidade Federal do Espírito Santo", "ES"),
    ("UNIRIO", "Universidade Federal do Estado do Rio de Janeiro", "RJ"),
    ("UFRJ", "Universidade Federal do Rio de Janeiro", "RJ"),
    ("UFTM", "Universidade Federal do Triângulo Mineiro", "MG"),
    ("UFVJM", "Universidade Federal dos Vales do Jequitinhonha e Mucuri", "MG"),
    ("UFF", "Universidade Federal Fluminense", "RJ"),
    ("UFRRJ", "Universidade Federal Rural do Rio de Janeiro", "RJ"),
    ("UTFPR", "Universidade Tecnológica Federal do Paraná", "PR"),
    ("UFFS", "Universidade Federal da Fronteira Sul", "SC"),
    ("UNILA", "Universidade Federal da Integração Latino-Americana", "PR"),
    ("UFCSPA", "Universidade Federal de Ciências da Saúde de Porto Alegre", "RS"),
    ("UFPel", "Universidade Federal de Pelotas", "RS"),
    ("UFSC", "Universidade Federal de Santa Catarina", "SC"),
    ("UFSM", "Universidade Federal de Santa Maria", "RS"),
    ("UNIPAMPA", "Universidade Federal do Pampa", "RS"),
    ("UFPR", "Universidade Federal do Paraná", "PR"),
    ("FURG", "Universidade Federal do Rio Grande", "RS"),
    ("UFRGS", "Universidade Federal do Rio Grande do Sul", "RS"),
    ("UFAPE", "Universidade Federal do Agreste de Pernambuco", "PE"),
    ("UFDPar", "Universidade Federal do Delta do Parnaíba", "PI"),
    ("UFNT", "Universidade Federal do Norte do Tocantins", "TO"),
)

# Institutos Federais (slug único, nome oficial, UF principal).
INSTITUTOS_FEDERAIS: tuple[tuple[str, str, str], ...] = (
    ("ifac", "Instituto Federal do Acre", "AC"),
    ("ifal", "Instituto Federal de Alagoas", "AL"),
    ("ifap", "Instituto Federal do Amapá", "AP"),
    ("ifam", "Instituto Federal do Amazonas", "AM"),
    ("ifba", "Instituto Federal da Bahia", "BA"),
    ("if_baiano", "Instituto Federal Baiano", "BA"),
    ("ifb", "Instituto Federal de Brasília", "DF"),
    ("ifce", "Instituto Federal de Educação, Ciência e Tecnologia do Ceará", "CE"),
    ("ifes", "Instituto Federal do Espírito Santo", "ES"),
    ("ifg", "Instituto Federal de Goiás", "GO"),
    ("if_goiano", "Instituto Federal Goiano", "GO"),
    ("ifma", "Instituto Federal do Maranhão", "MA"),
    ("ifmg", "Instituto Federal de Minas Gerais", "MG"),
    ("if_norte_mg", "Instituto Federal do Norte de Minas Gerais", "MG"),
    ("if_sudeste_mg", "Instituto Federal do Sudeste de Minas Gerais", "MG"),
    ("if_sul_mg", "Instituto Federal do Sul de Minas Gerais", "MG"),
    ("if_triangulo_mg", "Instituto Federal do Triângulo Mineiro", "MG"),
    ("ifmt", "Instituto Federal de Mato Grosso", "MT"),
    ("ifms", "Instituto Federal de Mato Grosso do Sul", "MS"),
    ("ifpa", "Instituto Federal do Pará", "PA"),
    ("ifpb", "Instituto Federal da Paraíba", "PB"),
    ("ifpe", "Instituto Federal de Pernambuco", "PE"),
    ("if_sertao_pe", "Instituto Federal do Sertão Pernambucano", "PE"),
    ("ifpi", "Instituto Federal do Piauí", "PI"),
    ("ifpr", "Instituto Federal do Paraná", "PR"),
    ("ifrj", "Instituto Federal do Rio de Janeiro", "RJ"),
    ("iff", "Instituto Federal Fluminense", "RJ"),
    ("ifrn", "Instituto Federal do Rio Grande do Norte", "RN"),
    ("ifrs", "Instituto Federal do Rio Grande do Sul", "RS"),
    ("if_farroupilha", "Instituto Federal Farroupilha", "RS"),
    ("if_sul_rs", "Instituto Federal Sul-rio-grandense", "RS"),
    ("ifro", "Instituto Federal de Rondônia", "RO"),
    ("ifrr", "Instituto Federal de Roraima", "RR"),
    ("ifsc", "Instituto Federal de Santa Catarina", "SC"),
    ("if_catarinense", "Instituto Federal Catarinense", "SC"),
    ("ifsp", "Instituto Federal de São Paulo", "SP"),
    ("ifse", "Instituto Federal de Sergipe", "SE"),
    ("ifto", "Instituto Federal do Tocantins", "TO"),
)
