"""
Catálogo estático para seed do diretório de órgãos públicos (referência institucional).
Executivo federal, autarquias e fundações/institutos federais frequentes; Judiciário usa TRF_SEDES + seeds por UF.
"""

from __future__ import annotations

# Presidência, órgãos centrais e ministérios (ajuste conforme reforma ministerial).
FEDERAL_EXECUTIVO_ITENS: tuple[tuple[str, str, str], ...] = (
    ("pr", "Presidência da República", "Chefe do Executivo federal"),
    ("vp", "Vice-Presidência da República", "Vice-presidência"),
    ("casacivil", "Casa Civil da Presidência da República", "Articulação política"),
    ("secom", "Secretaria de Comunicação Social", "Secom/PR"),
    ("sgi", "Secretaria-Geral da Presidência da República", "SGPR"),
    ("sri", "Secretaria de Relações Institucionais", "SRI"),
    ("gsi", "Gabinete de Segurança Institucional", "GSI/PR"),
    ("agu", "Advocacia-Geral da União", "AGU"),
    ("cgu", "Controladoria-Geral da União", "CGU"),
    ("mapa", "Ministério da Agricultura e Pecuária", "MAPA"),
    ("mda", "Ministério do Desenvolvimento Agrário e Agricultura Familiar", "MDA"),
    ("mcti", "Ministério da Ciência, Tecnologia e Inovação", "MCTI"),
    ("mcid", "Ministério da Cultura", "MinC"),
    ("mdef", "Ministério da Defesa", "MD"),
    ("mec", "Ministério da Educação", "MEC"),
    ("mf", "Ministério da Fazenda", "MF"),
    ("mgov", "Ministério da Gestão e Inovação em Serviços Públicos", "MGI"),
    ("mir", "Ministério da Igualdade Racial", "MIR"),
    ("midr", "Ministério da Integração e Desenvolvimento Regional", "MIDR"),
    ("mjsp", "Ministério da Justiça e Segurança Pública", "MJSP"),
    ("mulher", "Ministério das Mulheres", "MM"),
    ("mprev", "Ministério da Previdência Social", "MPrev"),
    ("ms", "Ministério da Saúde", "MS"),
    ("mre", "Ministério das Relações Exteriores", "MRE / Itamaraty"),
    ("mdsg", "Ministério do Desenvolvimento e Assistência Social", "MDS"),
    ("mesp", "Ministério do Esporte", "MEsp"),
    ("mma", "Ministério do Meio Ambiente e Mudança do Clima", "MMA"),
    ("mdhc", "Ministério dos Direitos Humanos e da Cidadania", "MDHC"),
    ("mpi", "Ministério dos Povos Indígenas", "MPI"),
    ("mtransp", "Ministério dos Transportes", "MT"),
    ("mte", "Ministério do Trabalho e Emprego", "MTE"),
    ("mtur", "Ministério do Turismo", "MTur"),
    ("mpabr", "Ministério de Portos e Aeroportos", "MPA"),
    ("mcom", "Ministério do Desenvolvimento, Indústria, Comércio e Serviços", "MDIC"),
)

# Autarquias, agências reguladoras, institutos e entidades da administração indireta federal (lista enxuta e única por slug).
AUTARQUIAS_FEDERAIS_UNICAS: tuple[tuple[str, str, str], ...] = (
    ("anac", "Agência Nacional de Aviação Civil", "ANAC"),
    ("ana", "Agência Nacional de Águas e Esgotos", "ANA"),
    ("aneel", "Agência Nacional de Energia Elétrica", "ANEEL"),
    ("anm", "Agência Nacional de Mineração", "ANM"),
    ("anp", "Agência Nacional do Petróleo", "ANP"),
    ("anpd", "Autoridade Nacional de Proteção de Dados", "ANPD"),
    ("ans", "Agência Nacional de Saúde Suplementar", "ANS"),
    ("antt", "Agência Nacional de Transportes Terrestres", "ANTT"),
    ("anvisa", "Agência Nacional de Vigilância Sanitária", "ANVISA"),
    ("ancine", "Agência Nacional do Cinema", "ANCINE"),
    ("anatel", "Agência Nacional de Telecomunicações", "Anatel"),
    ("susep", "Superintendência de Seguros Privados", "SUSEP"),
    ("previc", "Superintendência Nacional de Previdência Complementar", "Previc"),
    ("ibama", "Instituto Brasileiro do Meio Ambiente e dos Recursos Naturais Renováveis", "IBAMA"),
    ("icmbio", "Instituto Chico Mendes de Conservação da Biodiversidade", "ICMBio"),
    ("ibge", "Instituto Brasileiro de Geografia e Estatística", "IBGE"),
    ("inpe", "Instituto Nacional de Pesquisas Espaciais", "INPE"),
    ("inpi", "Instituto Nacional da Propriedade Industrial", "INPI"),
    ("inss", "Instituto Nacional do Seguro Social", "INSS"),
    ("inmetro", "Instituto Nacional de Metrologia, Qualidade e Tecnologia", "INMETRO"),
    ("incra", "Instituto Nacional de Colonização e Reforma Agrária", "INCRA"),
    ("dnit", "Departamento Nacional de Infraestrutura de Transportes", "DNIT"),
    ("embrapa", "Empresa Brasileira de Pesquisa Agropecuária", "Embrapa"),
    ("ebc", "Empresa Brasil de Comunicação", "EBC"),
    ("fiocruz", "Fundação Oswaldo Cruz", "Fiocruz"),
    ("finep", "Financiadora de Estudos e Projetos", "FINEP"),
    ("cnpq", "Conselho Nacional de Desenvolvimento Científico e Tecnológico", "CNPq"),
    ("capes", "Coordenação de Aperfeiçoamento de Pessoal de Nível Superior", "CAPES"),
    ("conab", "Companhia Nacional de Abastecimento", "CONAB"),
    ("itaipu", "Itaipu Binacional", "Itaipu"),
    ("correios", "Empresa Brasileira de Correios e Telégrafos", "Correios"),
    ("rnp", "Rede Nacional de Ensino e Pesquisa", "RNP"),
    ("iti", "Instituto Nacional de Tecnologia da Informação", "ITI"),
    ("bacen", "Banco Central do Brasil", "BCB"),
    ("cvm", "Comissão de Valores Mobiliários", "CVM"),
    ("suframa", "Superintendência da Zona Franca de Manaus", "Suframa"),
    ("funai", "Fundação Nacional dos Povos Indígenas", "FUNAI"),
    ("dataprev", "Dataprev — Tecnologia da Informação da Previdência", "Dataprev"),
    ("serpro", "Serviço Federal de Processamento de Dados", "Serpro"),
    ("rfb", "Secretaria Especial da Receita Federal do Brasil", "RFB"),
    ("pf", "Polícia Federal", "PF"),
    ("prf", "Polícia Rodoviária Federal", "PRF"),
    ("embratur", "Agência Brasileira de Promoção Internacional do Turismo", "Embratur"),
    ("abdi", "Agência Brasileira de Desenvolvimento Industrial", "ABDI"),
    ("apex", "Agência Brasileira de Promoção de Exportações e Investimentos", "ApexBrasil"),
    ("abin", "Agência Brasileira de Inteligência", "ABIN"),
    ("imprensa_nacional", "Imprensa Nacional", "Imprensa Nacional"),
    ("casa_moeda", "Casa da Moeda do Brasil", "CMB"),
    ("hemobras", "Hemobras — Hemoderivados e Biotecnologia", "Hemobras"),
    ("funarte", "Fundação Nacional de Artes", "Funarte"),
    ("ibict", "Instituto Brasileiro de Informação em Ciência e Tecnologia", "IBICT"),
    ("inpa", "Instituto Nacional de Pesquisas da Amazônia", "INPA"),
    ("ipea", "Instituto de Pesquisa Econômica Aplicada", "IPEA"),
    ("legado_funasa", "Fundação Nacional de Saúde (referência histórica)", "Funasa"),
)

# TRF sedes (UF da sede administrativa principal).
TRF_SEDES: tuple[tuple[str, str, str], ...] = (
    ("TRF1", "Tribunal Regional Federal da 1ª Região", "RJ"),
    ("TRF2", "Tribunal Regional Federal da 2ª Região", "SP"),
    ("TRF3", "Tribunal Regional Federal da 3ª Região", "MG"),
    ("TRF4", "Tribunal Regional Federal da 4ª Região", "RS"),
    ("TRF5", "Tribunal Regional Federal da 5ª Região", "BA"),
    ("TRF6", "Tribunal Regional Federal da 6ª Região", "PE"),
)

# TRT: 24 regiões — (nº região, UF sede, município sede).
# Referência: estrutura da Justiça do Trabalho (TST / tribunais regionais).
TRT_REGIOES: tuple[tuple[int, str, str], ...] = (
    (1, "RJ", "Rio de Janeiro"),
    (2, "SP", "São Paulo"),
    (3, "MG", "Belo Horizonte"),
    (4, "RS", "Porto Alegre"),
    (5, "BA", "Salvador"),
    (6, "PE", "Recife"),
    (7, "CE", "Fortaleza"),
    (8, "PA", "Belém"),
    (9, "PR", "Curitiba"),
    (10, "DF", "Brasília"),
    (11, "AM", "Manaus"),
    (12, "SC", "Florianópolis"),
    (13, "PB", "João Pessoa"),
    (14, "RO", "Porto Velho"),
    (15, "SP", "Campinas"),
    (16, "MA", "São Luís"),
    (17, "ES", "Vitória"),
    (18, "GO", "Goiânia"),
    (19, "AL", "Maceió"),
    (20, "SE", "Aracaju"),
    (21, "RN", "Natal"),
    (22, "PI", "Teresina"),
    (23, "MT", "Cuiabá"),
    (24, "MS", "Campo Grande"),
)

# Órgãos federais de segurança (PF e PRF já constam em autarquias federais — aqui só complementos).
SEGURANCA_FEDERAL_EXTRAS: tuple[tuple[str, str, str], ...] = (
    ("ppen", "Polícia Penal Federal", "Segurança nas unidades do sistema penitenciário federal"),
    (
        "forca_nacional",
        "Força Nacional de Segurança Pública",
        "Apoio a situações emergenciais e grandes eventos",
    ),
    (
        "senasp",
        "Secretaria Nacional de Segurança Pública",
        "SENASP — coordenação de políticas (MJSP)",
    ),
    ("depen", "Departamento Penitenciário Nacional", "DEPEN"),
)
